using System.Data;
using Maintenance.Common.Data;

namespace Maintenance.PagReport
{
    public class PagReportDataAccess : ImapDataAccess
    {
        public DataTable GetAllPagIndexes()
        {
            return Query(@"
SELECT I.INDEX_ID ID, I.INDEX_CD CODE, I.INDEX_LONG_NAME NAME,
MI.IS_HS_REPORT,
MI.IS_BARRA_REGIONAL,
MI.IS_BARRA_JAPAN,
MI.IS_BARRA_AUSTRALIA
FROM IMAP_APPS.PAG_MAINT_INDEX MI
JOIN IMAP_APPS.INDEX_BASIC I ON I.INDEX_ID = MI.INDEX_ID");
        }

        public DataTable GetAllPagPortfolios()
        {
            return Query(@"
SELECT P.PORTFOLIO_ID ID, P.PORTFOLIO_SHORT_NAME CODE, PORTFOLIO_LONG_NAME NAME,
MP.IS_HS_REPORT,
MP.IS_BARRA_REGIONAL,
MP.IS_BARRA_JAPAN,
MP.IS_BARRA_AUSTRALIA
FROM IMAP_APPS.PAG_MAINT_PORTFOLIO MP
JOIN IMAP_APPS.PORTFOLIO P ON MP.PORTFOLIO_ID = P.PORTFOLIO_ID");
        }

        public DataTable GetAllHeadStockOverrides()
        {
            return Query(@"
SELECT HEADSTOCK_TYPE_CD TYPE,
T1.TRADABLE_ENT_ID ID1, T1.FMRCUSIP CUSIP1, T1.SEDOL SEDOL1, I1.INSTRUMENT_SHORT_NAME NAME1,
T2.TRADABLE_ENT_ID ID2, T2.FMRCUSIP CUSIP2, T2.SEDOL SEDOL2, I2.INSTRUMENT_SHORT_NAME NAME2
FROM IMAP_APPS.PAG_HEADSTOCK_OVERRIDE HO
JOIN IMAP_APPS.TRADABLE_ENT T1 ON HO.TRADABLE_ENT_ID = T1.TRADABLE_ENT_ID
JOIN IMAP_APPS.TRADABLE_ENT T2 ON HO.TO_TRADABLE_ENT_ID = T2.TRADABLE_ENT_ID
JOIN IMAP_APPS.INSTRUMENT I1 ON T1.INSTRUMENT_ID = I1.INSTRUMENT_ID
JOIN IMAP_APPS.INSTRUMENT I2 ON T2.INSTRUMENT_ID = I2.INSTRUMENT_ID");
        }

        public DataTable GetAllBarraOverrides()
        {
            return Query(@"
SELECT BARRA_TYPE_CD TYPE, BARRA_ID,
T.TRADABLE_ENT_ID ID, T.FMRCUSIP CUSIP, T.SEDOL SEDOL, I.INSTRUMENT_SHORT_NAME NAME
FROM IMAP_APPS.PAG_BARRA_ID_OVERRIDE BIO
JOIN IMAP_APPS.TRADABLE_ENT T
ON BIO.TRADABLE_ENT_ID = T.TRADABLE_ENT_ID
JOIN IMAP_APPS.INSTRUMENT I
ON T.INSTRUMENT_ID = I.INSTRUMENT_ID");
        }
    }
}